# Copyright (c) 2019 Vitasystems GmbH and Hannover Medical School.
#
# This file is part of Project EHRbase
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ehrbase
    username: ehrbase
    password: ehrbase
    tomcat:
      maxIdle: 10
      max-active: 50
      max-wait: 10000

server:
  contextPath: /ehrbase
  port: 8080
  # Optional custom server nodename
  # nodename: 'local.test.org'

system:
  type: LOCAL


keycloak:
  bearer-only: true
  realm: demo
  resource: myclient
  use-resource-role-mappings: true
  auth-server-url: http://localhost:8090/auth